"""Reusable UI component helpers for the Streamlit chat interface."""

# UI label translations keyed by language name
_LABELS: dict[str, dict[str, str]] = {
    "English": {
        "step": "Step", "technology": "Technology", "strength": "Strength",
        "fit_score": "Fit Score", "availability": "Availability",
        "hrs_wk": "hrs/wk", "task": "Task", "skills": "Skills",
        "primary": "Primary", "support": "Support",
        "translating": "Translating to English…",
        "tech_label": "Technology / Tool",
        "original_label": "Original",
        "remove_label": "Remove",
        # ── UI chrome ──────────────────────────────────────────────────────
        "app_title": "Functional Consultant Resource Matcher",
        "app_subtitle": "Describe your project problem and get matched consultant resources.",
        "new_chat_btn": "🗨️ New Chat",
        "search_placeholder": "🔍 Search history…",
        "settings_heading": "Settings",
        "response_language_label": "Response language",
        "cache_info": "⚡ Cache: {n} prompts stored",
        "history_heading": "📋 History",
        "chat_placeholder": "Describe your project problem…",
        "chat_processing": "⏳ Pipeline running, please wait…",
        "edit_steps_btn": "✏️ Edit Steps",
        "edit_steps_heading": "✏️ Edit Steps",
        "regenerate_btn": "🔄 Regenerate Resources",
        "cancel_btn": "✖ Cancel",
        "add_step_btn": "➕ Add Step",
        "stop_btn": "🛑 Stop",
        "download_btn": "📥 Download Report (.docx)",
        "finish_editing_hint": "Finish editing before downloading",
        "edit_activate_hint": "Edit or add at least one step to enable",
        "load_btn": "Load",
        "close_btn": "Close",
        "rerun_btn": "🔄 Re-run",
        "step_desc_label": "Step description *",
        "step_desc_placeholder": "Describe what this step involves…",
        "effort_label": "Estimated effort",
        "effort_placeholder": "e.g. 2-3 days",
        "add_step_confirm": "Add Step",
        "step_desc_required": "Step description is required.",
        "edit_q_caption": "Edit your question below and re-run the pipeline with the updated version.",
        "preview_help": "Preview",
        "delete_help": "Delete from history",
        "needs_staffing": "Needs staffing review",
        "report_generated": "Report generated.",
        "breakdown_title": "Skill-Biased Project Breakdown",
        "task_recs_title": "Task Resource Recommendations",
        "resources_title": "Recommended Resources",
        "risk_title": "Risk Flags",
        "download_hint": "Use the download button to get your .docx file.",
        "model": "Model",
        "step_gathering": "Gathering project information...",
        "step_searching": "Searching web to clarify task lists...",
        "step_finding": "Finding resources with relevant skills from our database...",
        "step_matching": "Finding best match resources...",
        "step_finalizing": "Finalizing resource report",
    },
    "French": {
        "step": "Étape", "technology": "Technologie", "strength": "Force",
        "fit_score": "Score d'adéquation", "availability": "Disponibilité",
        "hrs_wk": "hrs/sem", "task": "Tâche", "skills": "Compétences",
        "primary": "Primaire", "support": "Support",
        "translating": "Traduction en cours en français…",
        "tech_label": "Technologie / Outil",
        "original_label": "Original",
        "remove_label": "Supprimer",
        "app_title": "Correspondance des Ressources Consultantes",
        "app_subtitle": "Décrivez votre problème de projet et obtenez des ressources consultantes adaptées.",
        "new_chat_btn": "🗨️ Nouvelle conversation",
        "search_placeholder": "🔍 Rechercher l'historique…",
        "settings_heading": "Paramètres",
        "response_language_label": "Langue de réponse",
        "cache_info": "⚡ Cache : {n} invite(s) stockée(s)",
        "history_heading": "📋 Historique",
        "chat_placeholder": "Décrivez votre problème de projet…",
        "chat_processing": "⏳ Pipeline en cours, veuillez patienter…",
        "edit_steps_btn": "✏️ Modifier les étapes",
        "edit_steps_heading": "✏️ Modifier les étapes",
        "regenerate_btn": "🔄 Régénérer les ressources",
        "cancel_btn": "✖ Annuler",
        "add_step_btn": "➕ Ajouter une étape",
        "stop_btn": "🛑 Arrêter",
        "download_btn": "📥 Télécharger le rapport (.docx)",
        "finish_editing_hint": "Terminez les modifications avant de télécharger",
        "edit_activate_hint": "Modifiez ou ajoutez au moins une étape pour activer",
        "load_btn": "Charger",
        "close_btn": "Fermer",
        "rerun_btn": "🔄 Relancer",
        "step_desc_label": "Description de l'étape *",
        "step_desc_placeholder": "Décrivez ce que cette étape implique…",
        "effort_label": "Effort estimé",
        "effort_placeholder": "ex. 2-3 jours",
        "add_step_confirm": "Ajouter l'étape",
        "step_desc_required": "La description de l'étape est obligatoire.",
        "edit_q_caption": "Modifiez votre question ci-dessous et relancez le pipeline.",
        "preview_help": "Aperçu",
        "delete_help": "Supprimer de l'historique",
        "needs_staffing": "Révision de dotation nécessaire",
        "report_generated": "Rapport généré.",
        "breakdown_title": "Décomposition du projet par compétences",
        "task_recs_title": "Recommandations de ressources par tâche",
        "resources_title": "Ressources recommandées",
        "risk_title": "Indicateurs de risque",
        "download_hint": "Utilisez le bouton de téléchargement pour obtenir votre fichier .docx.",
        "model": "Modèle",
        "step_gathering": "Collecte des informations du projet...",
        "step_searching": "Recherche web pour clarifier les listes de tâches...",
        "step_finding": "Recherche de ressources pertinentes dans notre base de données...",
        "step_matching": "Recherche des meilleures correspondances...",
        "step_finalizing": "Finalisation du rapport de ressources",
    },
    "German": {
        "step": "Schritt", "technology": "Technologie", "strength": "Stärke",
        "fit_score": "Eignungspunktzahl", "availability": "Verfügbarkeit",
        "hrs_wk": "Std/Wo", "task": "Aufgabe", "skills": "Fähigkeiten",
        "primary": "Primär", "support": "Unterstützung",
        "translating": "Übersetzung ins Deutsche läuft…",
        "tech_label": "Technologie / Werkzeug",
        "original_label": "Original",
        "remove_label": "Entfernen",
        "app_title": "Berater-Ressourcen-Zuordnung",
        "app_subtitle": "Beschreiben Sie Ihr Projektproblem und erhalten Sie passende Berater-Ressourcen.",
        "new_chat_btn": "🗨️ Neues Gespräch",
        "search_placeholder": "🔍 Verlauf durchsuchen…",
        "settings_heading": "Einstellungen",
        "response_language_label": "Antwortsprache",
        "cache_info": "⚡ Cache: {n} Abfrage(n) gespeichert",
        "history_heading": "📋 Verlauf",
        "chat_placeholder": "Beschreiben Sie Ihr Projektproblem…",
        "chat_processing": "⏳ Pipeline läuft, bitte warten…",
        "edit_steps_btn": "✏️ Schritte bearbeiten",
        "edit_steps_heading": "✏️ Schritte bearbeiten",
        "regenerate_btn": "🔄 Ressourcen neu generieren",
        "cancel_btn": "✖ Abbrechen",
        "add_step_btn": "➕ Schritt hinzufügen",
        "stop_btn": "🛑 Stopp",
        "download_btn": "📥 Bericht herunterladen (.docx)",
        "finish_editing_hint": "Bearbeitung abschließen vor dem Herunterladen",
        "edit_activate_hint": "Mindestens einen Schritt bearbeiten oder hinzufügen",
        "load_btn": "Laden",
        "close_btn": "Schließen",
        "rerun_btn": "🔄 Erneut ausführen",
        "step_desc_label": "Schrittbeschreibung *",
        "step_desc_placeholder": "Beschreiben Sie, was dieser Schritt beinhaltet…",
        "effort_label": "Geschätzter Aufwand",
        "effort_placeholder": "z.B. 2-3 Tage",
        "add_step_confirm": "Schritt hinzufügen",
        "step_desc_required": "Schrittbeschreibung ist erforderlich.",
        "edit_q_caption": "Bearbeiten Sie Ihre Frage unten und führen Sie die Pipeline erneut aus.",
        "preview_help": "Vorschau",
        "delete_help": "Aus dem Verlauf löschen",
        "needs_staffing": "Personaleinsatz überprüfen",
        "report_generated": "Bericht erstellt.",
        "breakdown_title": "Kompetenzbasierte Projektübersicht",
        "task_recs_title": "Aufgabenbasierte Ressourcenempfehlungen",
        "resources_title": "Empfohlene Ressourcen",
        "risk_title": "Risikohinweise",
        "download_hint": "Verwenden Sie die Download-Schaltfläche, um Ihre .docx-Datei zu erhalten.",
        "model": "Modell",
        "step_gathering": "Projektinformationen sammeln...",
        "step_searching": "Web-Suche zur Klärung von Aufgabenlisten...",
        "step_finding": "Ressourcen mit relevanten Fähigkeiten suchen...",
        "step_matching": "Beste Ressourcenübereinstimmungen finden...",
        "step_finalizing": "Ressourcenbericht finalisieren",
    },
    "Spanish": {
        "step": "Paso", "technology": "Tecnología", "strength": "Fortaleza",
        "fit_score": "Puntuación de ajuste", "availability": "Disponibilidad",
        "hrs_wk": "hrs/sem", "task": "Tarea", "skills": "Habilidades",
        "primary": "Primario", "support": "Soporte",
        "translating": "Traduciendo al español…",
        "tech_label": "Tecnología / Herramienta",
        "original_label": "Original",
        "remove_label": "Eliminar",
        "app_title": "Correspondencia de Recursos Consultores",
        "app_subtitle": "Describa su problema de proyecto y obtenga recursos consultores coincidentes.",
        "new_chat_btn": "🗨️ Nueva conversación",
        "search_placeholder": "🔍 Buscar historial…",
        "settings_heading": "Configuración",
        "response_language_label": "Idioma de respuesta",
        "cache_info": "⚡ Caché: {n} consulta(s) almacenada(s)",
        "history_heading": "📋 Historial",
        "chat_placeholder": "Describa su problema de proyecto…",
        "chat_processing": "⏳ Pipeline en ejecución, por favor espere…",
        "edit_steps_btn": "✏️ Editar pasos",
        "edit_steps_heading": "✏️ Editar pasos",
        "regenerate_btn": "🔄 Regenerar recursos",
        "cancel_btn": "✖ Cancelar",
        "add_step_btn": "➕ Agregar paso",
        "stop_btn": "🛑 Detener",
        "download_btn": "📥 Descargar informe (.docx)",
        "finish_editing_hint": "Termine la edición antes de descargar",
        "edit_activate_hint": "Edite o agregue al menos un paso para activar",
        "load_btn": "Cargar",
        "close_btn": "Cerrar",
        "rerun_btn": "🔄 Volver a ejecutar",
        "step_desc_label": "Descripción del paso *",
        "step_desc_placeholder": "Describa lo que implica este paso…",
        "effort_label": "Esfuerzo estimado",
        "effort_placeholder": "ej. 2-3 días",
        "add_step_confirm": "Agregar paso",
        "step_desc_required": "La descripción del paso es obligatoria.",
        "edit_q_caption": "Edite su pregunta a continuación y vuelva a ejecutar el pipeline.",
        "preview_help": "Vista previa",
        "delete_help": "Eliminar del historial",
        "needs_staffing": "Requiere revisión de personal",
        "report_generated": "Informe generado.",
        "breakdown_title": "Desglose del proyecto por habilidades",
        "task_recs_title": "Recomendaciones de recursos por tarea",
        "resources_title": "Recursos recomendados",
        "risk_title": "Indicadores de riesgo",
        "download_hint": "Use el botón de descarga para obtener su archivo .docx.",
        "model": "Modelo",
        "step_gathering": "Recopilando información del proyecto...",
        "step_searching": "Buscando en la web para aclarar listas de tareas...",
        "step_finding": "Buscando recursos con habilidades relevantes...",
        "step_matching": "Encontrando los mejores recursos coincidentes...",
        "step_finalizing": "Finalizando el informe de recursos",
    },
    "Portuguese": {
        "step": "Passo", "technology": "Tecnologia", "strength": "Força",
        "fit_score": "Pontuação de adequação", "availability": "Disponibilidade",
        "hrs_wk": "hrs/sem", "task": "Tarefa", "skills": "Habilidades",
        "primary": "Primário", "support": "Suporte",
        "translating": "Traduzindo para português…",
        "tech_label": "Tecnologia / Ferramenta",
        "original_label": "Original",
        "remove_label": "Remover",
        "app_title": "Correspondência de Recursos Consultores",
        "app_subtitle": "Descreva o problema do seu projeto e obtenha recursos consultores correspondentes.",
        "new_chat_btn": "🗨️ Nova conversa",
        "search_placeholder": "🔍 Pesquisar histórico…",
        "settings_heading": "Configurações",
        "response_language_label": "Idioma da resposta",
        "cache_info": "⚡ Cache: {n} consulta(s) armazenada(s)",
        "history_heading": "📋 Histórico",
        "chat_placeholder": "Descreva o problema do seu projeto…",
        "chat_processing": "⏳ Pipeline em execução, aguarde…",
        "edit_steps_btn": "✏️ Editar etapas",
        "edit_steps_heading": "✏️ Editar etapas",
        "regenerate_btn": "🔄 Regenerar recursos",
        "cancel_btn": "✖ Cancelar",
        "add_step_btn": "➕ Adicionar etapa",
        "stop_btn": "🛑 Parar",
        "download_btn": "📥 Baixar relatório (.docx)",
        "finish_editing_hint": "Conclua a edição antes de baixar",
        "edit_activate_hint": "Edite ou adicione pelo menos uma etapa para ativar",
        "load_btn": "Carregar",
        "close_btn": "Fechar",
        "rerun_btn": "🔄 Executar novamente",
        "step_desc_label": "Descrição da etapa *",
        "step_desc_placeholder": "Descreva o que esta etapa envolve…",
        "effort_label": "Esforço estimado",
        "effort_placeholder": "ex. 2-3 dias",
        "add_step_confirm": "Adicionar etapa",
        "step_desc_required": "A descrição da etapa é obrigatória.",
        "edit_q_caption": "Edite sua pergunta abaixo e execute novamente o pipeline.",
        "preview_help": "Visualizar",
        "delete_help": "Excluir do histórico",
        "needs_staffing": "Necessita revisão de equipe",
        "report_generated": "Relatório gerado.",
        "breakdown_title": "Divisão do projeto por habilidades",
        "task_recs_title": "Recomendações de recursos por tarefa",
        "resources_title": "Recursos recomendados",
        "risk_title": "Sinalizadores de risco",
        "download_hint": "Use o botão de download para obter seu arquivo .docx.",
        "model": "Modelo",
        "step_gathering": "Reunindo informações do projeto...",
        "step_searching": "Pesquisando na web para esclarecer listas de tarefas...",
        "step_finding": "Encontrando recursos com habilidades relevantes...",
        "step_matching": "Encontrando os melhores recursos correspondentes...",
        "step_finalizing": "Finalizando relatório de recursos",
    },
    "Hindi": {
        "step": "चरण", "technology": "तकनीक", "strength": "शक्ति",
        "fit_score": "फिट स्कोर", "availability": "उपलब्धता",
        "hrs_wk": "घंटे/सप्ताह", "task": "कार्य", "skills": "कौशल",
        "primary": "प्राथमिक", "support": "सहायक",
        "translating": "हिंदी में अनुवाद हो रहा है…",
        "tech_label": "तकनीक / उपकरण",
        "original_label": "मूल पाठ",
        "remove_label": "हटाएं",
        "app_title": "कार्यात्मक परामर्शदाता संसाधन मिलानकर्ता",
        "app_subtitle": "अपनी परियोजना की समस्या बताएं और मिलान किए गए परामर्शदाता संसाधन प्राप्त करें।",
        "new_chat_btn": "🗨️ नई बातचीत",
        "search_placeholder": "🔍 इतिहास खोजें…",
        "settings_heading": "सेटिंग्स",
        "response_language_label": "प्रतिक्रिया भाषा",
        "cache_info": "⚡ कैश: {n} प्रॉम्प्ट संग्रहीत",
        "history_heading": "📋 इतिहास",
        "chat_placeholder": "अपनी परियोजना की समस्या बताएं…",
        "chat_processing": "⏳ पाइपलाइन चल रही है, कृपया प्रतीक्षा करें…",
        "edit_steps_btn": "✏️ चरण संपादित करें",
        "edit_steps_heading": "✏️ चरण संपादित करें",
        "regenerate_btn": "🔄 संसाधन पुनः उत्पन्न करें",
        "cancel_btn": "✖ रद्द करें",
        "add_step_btn": "➕ चरण जोड़ें",
        "stop_btn": "🛑 रोकें",
        "download_btn": "📥 रिपोर्ट डाउनलोड करें (.docx)",
        "finish_editing_hint": "डाउनलोड करने से पहले संपादन समाप्त करें",
        "edit_activate_hint": "सक्रिय करने के लिए कम से कम एक चरण संपादित करें या जोड़ें",
        "load_btn": "लोड करें",
        "close_btn": "बंद करें",
        "rerun_btn": "🔄 पुनः चलाएं",
        "step_desc_label": "चरण विवरण *",
        "step_desc_placeholder": "बताएं इस चरण में क्या शामिल है…",
        "effort_label": "अनुमानित प्रयास",
        "effort_placeholder": "जैसे 2-3 दिन",
        "add_step_confirm": "चरण जोड़ें",
        "step_desc_required": "चरण विवरण आवश्यक है।",
        "edit_q_caption": "अपना प्रश्न नीचे संपादित करें और अद्यतन संस्करण के साथ पाइपलाइन पुनः चलाएं।",
        "preview_help": "पूर्वावलोकन",
        "delete_help": "इतिहास से हटाएं",
        "needs_staffing": "स्टाफिंग समीक्षा आवश्यक",
        "report_generated": "रिपोर्ट तैयार।",
        "breakdown_title": "कौशल-आधारित परियोजना विवरण",
        "task_recs_title": "कार्य संसाधन अनुशंसाएं",
        "resources_title": "अनुशंसित संसाधन",
        "risk_title": "जोखिम संकेत",
        "download_hint": "अपनी .docx फ़ाइल प्राप्त करने के लिए डाउनलोड बटन का उपयोग करें।",
        "model": "मॉडल",
        "step_gathering": "परियोजना की जानकारी एकत्र करना...",
        "step_searching": "कार्य सूचियों को स्पष्ट करने के लिए वेब खोज...",
        "step_finding": "हमारे डेटाबेस से प्रासंगिक कौशल वाले संसाधन खोजना...",
        "step_matching": "सर्वश्रेष्ठ मिलान संसाधन खोजना...",
        "step_finalizing": "संसाधन रिपोर्ट अंतिम रूप देना",
    },
    "Arabic": {
        "step": "خطوة", "technology": "تقنية", "strength": "قوة",
        "fit_score": "درجة الملاءمة", "availability": "التوفر",
        "hrs_wk": "ساعة/أسبوع", "task": "مهمة", "skills": "المهارات",
        "primary": "أساسي", "support": "داعم",
        "translating": "جارٍ الترجمة إلى العربية…",
        "tech_label": "التقنية / الأداة",
        "original_label": "النص الأصلي",
        "remove_label": "إزالة",
        "app_title": "مطابقة الموارد الاستشارية",
        "app_subtitle": "صف مشكلة مشروعك واحصل على موارد استشارية مطابقة.",
        "new_chat_btn": "🗨️ محادثة جديدة",
        "search_placeholder": "🔍 البحث في السجل…",
        "settings_heading": "الإعدادات",
        "response_language_label": "لغة الاستجابة",
        "cache_info": "⚡ ذاكرة التخزين: {n} استعلام/استعلامات مخزنة",
        "history_heading": "📋 السجل",
        "chat_placeholder": "صف مشكلة مشروعك…",
        "chat_processing": "⏳ جارٍ تشغيل خط الأنابيب، يرجى الانتظار…",
        "edit_steps_btn": "✏️ تحرير الخطوات",
        "edit_steps_heading": "✏️ تحرير الخطوات",
        "regenerate_btn": "🔄 إعادة إنشاء الموارد",
        "cancel_btn": "✖ إلغاء",
        "add_step_btn": "➕ إضافة خطوة",
        "stop_btn": "🛑 إيقاف",
        "download_btn": "📥 تنزيل التقرير (.docx)",
        "finish_editing_hint": "أتمم التحرير قبل التنزيل",
        "edit_activate_hint": "حرر أو أضف خطوة واحدة على الأقل للتفعيل",
        "load_btn": "تحميل",
        "close_btn": "إغلاق",
        "rerun_btn": "🔄 إعادة التشغيل",
        "step_desc_label": "وصف الخطوة *",
        "step_desc_placeholder": "صف ما تتضمنه هذه الخطوة…",
        "effort_label": "الجهد المقدر",
        "effort_placeholder": "مثال: 2-3 أيام",
        "add_step_confirm": "إضافة خطوة",
        "step_desc_required": "وصف الخطوة مطلوب.",
        "edit_q_caption": "حرر سؤالك أدناه وأعد تشغيل خط الأنابيب بالنسخة المحدثة.",
        "preview_help": "معاينة",
        "delete_help": "حذف من السجل",
        "needs_staffing": "يحتاج مراجعة التوظيف",
        "report_generated": "تم إنشاء التقرير.",
        "breakdown_title": "تفصيل المشروع حسب المهارات",
        "task_recs_title": "توصيات موارد المهام",
        "resources_title": "الموارد الموصى بها",
        "risk_title": "علامات المخاطر",
        "download_hint": "استخدم زر التنزيل للحصول على ملف .docx الخاص بك.",
        "model": "النموذج",
        "step_gathering": "جمع معلومات المشروع...",
        "step_searching": "البحث في الويب لتوضيح قوائم المهام...",
        "step_finding": "البحث عن موارد ذات مهارات ذات صلة...",
        "step_matching": "البحث عن أفضل الموارد المطابقة...",
        "step_finalizing": "إتمام تقرير الموارد",
    },
    "Japanese": {
        "step": "ステップ", "technology": "技術", "strength": "強度",
        "fit_score": "適合スコア", "availability": "稼働時間",
        "hrs_wk": "時間/週", "task": "タスク", "skills": "スキル",
        "primary": "主担当", "support": "サポート",
        "translating": "日本語に翻訳中…",
        "tech_label": "技術 / ツール",
        "original_label": "原文",
        "remove_label": "削除",
        "app_title": "コンサルタントリソースマッチャー",
        "app_subtitle": "プロジェクトの問題を説明し、マッチしたコンサルタントリソースを取得してください。",
        "new_chat_btn": "🗨️ 新しいチャット",
        "search_placeholder": "🔍 履歴を検索…",
        "settings_heading": "設定",
        "response_language_label": "応答言語",
        "cache_info": "⚡ キャッシュ: {n}件のプロンプトを保存",
        "history_heading": "📋 履歴",
        "chat_placeholder": "プロジェクトの問題を説明してください…",
        "chat_processing": "⏳ パイプライン実行中、しばらくお待ちください…",
        "edit_steps_btn": "✏️ ステップを編集",
        "edit_steps_heading": "✏️ ステップを編集",
        "regenerate_btn": "🔄 リソースを再生成",
        "cancel_btn": "✖ キャンセル",
        "add_step_btn": "➕ ステップを追加",
        "stop_btn": "🛑 停止",
        "download_btn": "📥 レポートをダウンロード (.docx)",
        "finish_editing_hint": "ダウンロード前に編集を完了してください",
        "edit_activate_hint": "少なくとも1つのステップを編集または追加してください",
        "load_btn": "読み込む",
        "close_btn": "閉じる",
        "rerun_btn": "🔄 再実行",
        "step_desc_label": "ステップの説明 *",
        "step_desc_placeholder": "このステップの内容を説明してください…",
        "effort_label": "推定工数",
        "effort_placeholder": "例: 2-3日",
        "add_step_confirm": "ステップを追加",
        "step_desc_required": "ステップの説明は必須です。",
        "edit_q_caption": "質問を下で編集し、更新されたバージョンでパイプラインを再実行してください。",
        "preview_help": "プレビュー",
        "delete_help": "履歴から削除",
        "needs_staffing": "スタッフィングレビューが必要",
        "report_generated": "レポートが生成されました。",
        "breakdown_title": "スキルベースのプロジェクト概要",
        "task_recs_title": "タスクリソース推薦",
        "resources_title": "推奨リソース",
        "risk_title": "リスクフラグ",
        "download_hint": "ダウンロードボタンを使用して.docxファイルを取得してください。",
        "model": "モデル",
        "step_gathering": "プロジェクト情報を収集中...",
        "step_searching": "タスクリストを明確にするためのウェブ検索...",
        "step_finding": "データベースから関連スキルを持つリソースを検索中...",
        "step_matching": "最適なリソースを検索中...",
        "step_finalizing": "リソースレポートを確定中",
    },
    "Chinese (Simplified)": {
        "step": "步骤", "technology": "技术", "strength": "强度",
        "fit_score": "匹配分数", "availability": "可用时间",
        "hrs_wk": "小时/周", "task": "任务", "skills": "技能",
        "primary": "主要", "support": "支持",
        "translating": "正在翻译成中文…",
        "tech_label": "技术 / 工具",
        "original_label": "原文",
        "remove_label": "删除",
        "app_title": "顾问资源匹配器",
        "app_subtitle": "描述您的项目问题，获取匹配的顾问资源。",
        "new_chat_btn": "🗨️ 新对话",
        "search_placeholder": "🔍 搜索历史…",
        "settings_heading": "设置",
        "response_language_label": "响应语言",
        "cache_info": "⚡ 缓存：已存储 {n} 条提示",
        "history_heading": "📋 历史记录",
        "chat_placeholder": "描述您的项目问题…",
        "chat_processing": "⏳ 管道运行中，请稍候…",
        "edit_steps_btn": "✏️ 编辑步骤",
        "edit_steps_heading": "✏️ 编辑步骤",
        "regenerate_btn": "🔄 重新生成资源",
        "cancel_btn": "✖ 取消",
        "add_step_btn": "➕ 添加步骤",
        "stop_btn": "🛑 停止",
        "download_btn": "📥 下载报告 (.docx)",
        "finish_editing_hint": "请在下载前完成编辑",
        "edit_activate_hint": "请至少编辑或添加一个步骤以激活",
        "load_btn": "加载",
        "close_btn": "关闭",
        "rerun_btn": "🔄 重新运行",
        "step_desc_label": "步骤描述 *",
        "step_desc_placeholder": "描述该步骤涉及的内容…",
        "effort_label": "预计工时",
        "effort_placeholder": "例如 2-3 天",
        "add_step_confirm": "添加步骤",
        "step_desc_required": "步骤描述是必填项。",
        "edit_q_caption": "在下方编辑您的问题，然后使用更新后的版本重新运行管道。",
        "preview_help": "预览",
        "delete_help": "从历史记录中删除",
        "needs_staffing": "需要人员审查",
        "report_generated": "报告已生成。",
        "breakdown_title": "基于技能的项目分解",
        "task_recs_title": "任务资源建议",
        "resources_title": "推荐资源",
        "risk_title": "风险标志",
        "download_hint": "使用下载按钮获取您的.docx文件。",
        "model": "模型",
        "step_gathering": "收集项目信息...",
        "step_searching": "搜索网络以明确任务列表...",
        "step_finding": "从我们的数据库中查找具有相关技能的资源...",
        "step_matching": "寻找最佳匹配资源...",
        "step_finalizing": "完成资源报告",
    },
}


def get_labels(language: str = "English") -> dict[str, str]:
    """Return UI label translations for the given language."""
    return _LABELS.get(language, _LABELS["English"])


def get_workflow_steps(language: str = "English") -> list[dict]:
    """Return translated workflow step definitions."""
    lb = get_labels(language)
    return [
        {"key": "gathering", "icon": "🔄", "label": lb["step_gathering"]},
        {"key": "searching", "icon": "🔄", "label": lb["step_searching"]},
        {"key": "finding_skills", "icon": "🔄", "label": lb["step_finding"]},
        {"key": "matching", "icon": "🔄", "label": lb["step_matching"]},
        {"key": "finalizing", "icon": "✅", "label": lb["step_finalizing"]},
    ]


# Default English workflow steps (used where language isn't available)
WORKFLOW_STEPS = get_workflow_steps("English")

# Maps LangGraph node names to workflow step indices
NODE_STEP_MAP = {
    "load_resources": 0,
    "web_search": 1,
    "compute_strength": 2,
    "generate_solution": 3,
    "score_resources": 3,
    "generate_report": 4,
}


def format_solution_step(step: dict, language: str = "English") -> str:
    """Format a single solution step for display in chat."""
    lb = get_labels(language)
    return (
        f"**{lb['step']} {step.get('step', '?')}**: "
        f"{step.get('action', 'N/A')}  \n"
        f"{lb['technology']}: `{step.get('technology', 'N/A')}` "
        f"| {lb['strength']}: **{step.get('skill_strength_score', 'N/A')}**"
    )


def format_resource_card(resource: dict, language: str = "English") -> str:
    """Format a resource recommendation for display."""
    lb = get_labels(language)
    skills = resource.get("matched_skills", [])
    skills_str = (", ".join(skills[:4]) if skills else "")
    skills_part = f"  \n{lb['skills']}: {skills_str}" if skills_str else ""
    return (
        f"**{resource.get('full_name', 'N/A')}** "
        f"[{resource.get('priority', 'N/A')}]  \n"
        f"{lb['fit_score']}: **{resource.get('fit_score', 0):.2f}** "
        f"| {lb['availability']}: {resource.get('availability', 0)} {lb['hrs_wk']}"
        f"{skills_part}"
    )


_PROGRESS: dict[str, dict] = {
    "English": {
        "fixed": {},  # English is the source; no translation needed
        "patterns": [],
    },
    "Hindi": {
        "fixed": {
            "Loading consultant database...": "परामर्शदाता डेटाबेस लोड हो रहा है...",
            "Searching web for context...": "संदर्भ के लिए वेब खोज...",
            "Running Tavily search...": "Tavily खोज चल रही है...",
            "LLM extracting skills from results...": "LLM परिणामों से कौशल निकाल रहा है...",
            "Computing semantic skill matches...": "अर्थपूर्ण कौशल मिलान की गणना...",
            "Loading semantic matcher...": "अर्थपूर्ण मिलानकर्ता लोड हो रहा है...",
            "Generating skill-biased solution...": "कौशल-आधारित समाधान तैयार किया जा रहा है...",
            "Scoring resource fit...": "संसाधन फिट स्कोर की गणना...",
            "Generating .docx report...": ".docx रिपोर्ट तैयार की जा रही है...",
            "Report ready": "रिपोर्ट तैयार",
        },
        "patterns": [
            (r"Extracted (\d+) required skills", "{0} आवश्यक कौशल निकाले गए"),
            (r"Loaded (\d+) users, (\d+) skills", "{0} उपयोगकर्ता, {1} कौशल लोड किए"),
            (r"Matched (\d+) skills semantically", "{0} कौशल अर्थपूर्ण रूप से मिलाए गए"),
            (r"Created (\d+) solution steps", "{0} समाधान चरण बनाए गए"),
            (r"Ranked (\d+) resources across (\d+) tasks", "{1} कार्यों में {0} संसाधनों को रैंक किया"),
            (r"Using cached results \((\d+) skills\)", "कैश्ड परिणाम ({0} कौशल)"),
        ],
    },
    "French": {
        "fixed": {
            "Loading consultant database...": "Chargement de la base de données...",
            "Searching web for context...": "Recherche web en cours...",
            "Running Tavily search...": "Recherche Tavily en cours...",
            "LLM extracting skills from results...": "Extraction des compétences par LLM...",
            "Computing semantic skill matches...": "Calcul des correspondances sémantiques...",
            "Loading semantic matcher...": "Chargement du moteur sémantique...",
            "Generating skill-biased solution...": "Génération du plan de solution...",
            "Scoring resource fit...": "Calcul de l'adéquation des ressources...",
            "Generating .docx report...": "Génération du rapport .docx...",
            "Report ready": "Rapport prêt",
        },
        "patterns": [
            (r"Extracted (\d+) required skills", "{0} compétences extraites"),
            (r"Loaded (\d+) users, (\d+) skills", "{0} utilisateurs, {1} compétences chargés"),
            (r"Matched (\d+) skills semantically", "{0} compétences associées sémantiquement"),
            (r"Created (\d+) solution steps", "{0} étapes de solution créées"),
            (r"Ranked (\d+) resources across (\d+) tasks", "{0} ressources classées sur {1} tâches"),
            (r"Using cached results \((\d+) skills\)", "Résultats mis en cache ({0} compétences)"),
        ],
    },
    "German": {
        "fixed": {
            "Loading consultant database...": "Beraterdatenbank wird geladen...",
            "Searching web for context...": "Web-Suche läuft...",
            "Running Tavily search...": "Tavily-Suche läuft...",
            "LLM extracting skills from results...": "LLM extrahiert Fähigkeiten...",
            "Computing semantic skill matches...": "Semantische Übereinstimmungen werden berechnet...",
            "Loading semantic matcher...": "Semantischer Matcher wird geladen...",
            "Generating skill-biased solution...": "Lösung wird generiert...",
            "Scoring resource fit...": "Ressourcen-Eignung wird bewertet...",
            "Generating .docx report...": ".docx-Bericht wird erstellt...",
            "Report ready": "Bericht fertig",
        },
        "patterns": [
            (r"Extracted (\d+) required skills", "{0} Fähigkeiten extrahiert"),
            (r"Loaded (\d+) users, (\d+) skills", "{0} Nutzer, {1} Fähigkeiten geladen"),
            (r"Matched (\d+) skills semantically", "{0} Fähigkeiten semantisch zugeordnet"),
            (r"Created (\d+) solution steps", "{0} Lösungsschritte erstellt"),
            (r"Ranked (\d+) resources across (\d+) tasks", "{0} Ressourcen in {1} Aufgaben eingestuft"),
            (r"Using cached results \((\d+) skills\)", "Gespeicherte Ergebnisse ({0} Fähigkeiten)"),
        ],
    },
    "Spanish": {
        "fixed": {
            "Loading consultant database...": "Cargando base de datos de consultores...",
            "Searching web for context...": "Buscando en la web...",
            "Running Tavily search...": "Ejecutando búsqueda Tavily...",
            "LLM extracting skills from results...": "LLM extrayendo habilidades...",
            "Computing semantic skill matches...": "Calculando coincidencias semánticas...",
            "Loading semantic matcher...": "Cargando motor semántico...",
            "Generating skill-biased solution...": "Generando plan de solución...",
            "Scoring resource fit...": "Evaluando adecuación de recursos...",
            "Generating .docx report...": "Generando informe .docx...",
            "Report ready": "Informe listo",
        },
        "patterns": [
            (r"Extracted (\d+) required skills", "{0} habilidades extraídas"),
            (r"Loaded (\d+) users, (\d+) skills", "{0} usuarios, {1} habilidades cargadas"),
            (r"Matched (\d+) skills semantically", "{0} habilidades emparejadas semánticamente"),
            (r"Created (\d+) solution steps", "{0} pasos de solución creados"),
            (r"Ranked (\d+) resources across (\d+) tasks", "{0} recursos clasificados en {1} tareas"),
            (r"Using cached results \((\d+) skills\)", "Resultados en caché ({0} habilidades)"),
        ],
    },
    "Portuguese": {
        "fixed": {
            "Loading consultant database...": "Carregando base de dados de consultores...",
            "Searching web for context...": "Pesquisando na web...",
            "Running Tavily search...": "Executando pesquisa Tavily...",
            "LLM extracting skills from results...": "LLM extraindo habilidades...",
            "Computing semantic skill matches...": "Calculando correspondências semânticas...",
            "Loading semantic matcher...": "Carregando motor semântico...",
            "Generating skill-biased solution...": "Gerando plano de solução...",
            "Scoring resource fit...": "Avaliando adequação de recursos...",
            "Generating .docx report...": "Gerando relatório .docx...",
            "Report ready": "Relatório pronto",
        },
        "patterns": [
            (r"Extracted (\d+) required skills", "{0} habilidades extraídas"),
            (r"Loaded (\d+) users, (\d+) skills", "{0} usuários, {1} habilidades carregadas"),
            (r"Matched (\d+) skills semantically", "{0} habilidades correspondidas semanticamente"),
            (r"Created (\d+) solution steps", "{0} etapas de solução criadas"),
            (r"Ranked (\d+) resources across (\d+) tasks", "{0} recursos classificados em {1} tarefas"),
            (r"Using cached results \((\d+) skills\)", "Resultados em cache ({0} habilidades)"),
        ],
    },
    "Arabic": {
        "fixed": {
            "Loading consultant database...": "جارٍ تحميل قاعدة بيانات المستشارين...",
            "Searching web for context...": "جارٍ البحث على الويب...",
            "Running Tavily search...": "جارٍ تشغيل بحث Tavily...",
            "LLM extracting skills from results...": "جارٍ استخراج المهارات بواسطة LLM...",
            "Computing semantic skill matches...": "جارٍ حساب التطابقات الدلالية...",
            "Loading semantic matcher...": "جارٍ تحميل المطابق الدلالي...",
            "Generating skill-biased solution...": "جارٍ إنشاء خطة الحل...",
            "Scoring resource fit...": "جارٍ تقييم ملاءمة الموارد...",
            "Generating .docx report...": "جارٍ إنشاء تقرير .docx...",
            "Report ready": "التقرير جاهز",
        },
        "patterns": [
            (r"Extracted (\d+) required skills", "تم استخراج {0} مهارة مطلوبة"),
            (r"Loaded (\d+) users, (\d+) skills", "تم تحميل {0} مستخدم و{1} مهارة"),
            (r"Matched (\d+) skills semantically", "تمت مطابقة {0} مهارة دلاليًا"),
            (r"Created (\d+) solution steps", "تم إنشاء {0} خطوة حل"),
            (r"Ranked (\d+) resources across (\d+) tasks", "تم ترتيب {0} مورد في {1} مهمة"),
            (r"Using cached results \((\d+) skills\)", "استخدام نتائج مخزنة ({0} مهارات)"),
        ],
    },
    "Japanese": {
        "fixed": {
            "Loading consultant database...": "コンサルタントデータベースを読み込み中...",
            "Searching web for context...": "ウェブ検索中...",
            "Running Tavily search...": "Tavily検索を実行中...",
            "LLM extracting skills from results...": "LLMがスキルを抽出中...",
            "Computing semantic skill matches...": "意味的スキル照合を計算中...",
            "Loading semantic matcher...": "意味的マッチャーを読み込み中...",
            "Generating skill-biased solution...": "ソリューションプランを生成中...",
            "Scoring resource fit...": "リソース適合度を評価中...",
            "Generating .docx report...": ".docxレポートを生成中...",
            "Report ready": "レポート完成",
        },
        "patterns": [
            (r"Extracted (\d+) required skills", "{0}件の必要スキルを抽出"),
            (r"Loaded (\d+) users, (\d+) skills", "{0}人のユーザー、{1}スキルを読み込み"),
            (r"Matched (\d+) skills semantically", "{0}スキルを意味的に照合"),
            (r"Created (\d+) solution steps", "{0}ステップのソリューションを作成"),
            (r"Ranked (\d+) resources across (\d+) tasks", "{1}タスクで{0}リソースをランク付け"),
            (r"Using cached results \((\d+) skills\)", "キャッシュ結果を使用（{0}スキル）"),
        ],
    },
    "Chinese (Simplified)": {
        "fixed": {
            "Loading consultant database...": "正在加载顾问数据库...",
            "Searching web for context...": "正在网络搜索...",
            "Running Tavily search...": "正在运行Tavily搜索...",
            "LLM extracting skills from results...": "LLM正在提取技能...",
            "Computing semantic skill matches...": "正在计算语义技能匹配...",
            "Loading semantic matcher...": "正在加载语义匹配器...",
            "Generating skill-biased solution...": "正在生成解决方案计划...",
            "Scoring resource fit...": "正在评估资源匹配度...",
            "Generating .docx report...": "正在生成.docx报告...",
            "Report ready": "报告已完成",
        },
        "patterns": [
            (r"Extracted (\d+) required skills", "已提取{0}项所需技能"),
            (r"Loaded (\d+) users, (\d+) skills", "已加载{0}位用户、{1}项技能"),
            (r"Matched (\d+) skills semantically", "已语义匹配{0}项技能"),
            (r"Created (\d+) solution steps", "已创建{0}个解决方案步骤"),
            (r"Ranked (\d+) resources across (\d+) tasks", "已在{1}个任务中对{0}个资源排名"),
            (r"Using cached results \((\d+) skills\)", "使用缓存结果（{0}项技能）"),
        ],
    },
}


def translate_progress(status: str, language: str = "English") -> str:
    """Translate a backend progress status string to the selected language."""
    if language == "English" or language not in _PROGRESS:
        return status
    import re
    lang = _PROGRESS[language]
    if status in lang["fixed"]:
        return lang["fixed"][status]
    for pattern, template in lang["patterns"]:
        m = re.match(pattern, status)
        if m:
            return template.format(*m.groups())
    return status


def format_task_recommendation(task: dict, language: str = "English") -> str:
    """Format a task-level staffing recommendation."""
    lb = get_labels(language)
    resources = task.get("resources", [])
    _rec_map = {"Primary": lb["primary"], "Support": lb["support"]}
    resource_lines = []
    for r in resources:
        skills = r.get("matched_skills", [])
        skills_str = (", ".join(skills[:4]) if skills else "")
        skills_part = f" · {skills_str}" if skills_str else ""
        rec_label = _rec_map.get(r.get("recommendation", ""), r.get("recommendation", "Recommended"))
        resource_lines.append(
            f"{rec_label}: "
            f"**{r.get('full_name', 'N/A')}** "
            f"({lb['fit_score'].lower()} {r.get('fit_score', 0):.2f}, "
            f"{r.get('availability', 0)} {lb['hrs_wk']})"
            f"{skills_part}"
        )
    if not resource_lines:
        resource_lines = [lb["needs_staffing"]]
    skills = ", ".join(task.get("required_skills", [])) or "N/A"
    return (
        f"**{lb['task']} {task.get('task_id', '?')}: "
        f"{task.get('task', 'N/A')}**  \n"
        f"{lb['skills']}: `{skills}` | {lb['strength']}: "
        f"**{task.get('strength_score', 0):.2f}**  \n"
        + "  \n".join(resource_lines)
    )
